server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: dev
          uri: https://github.com/Markos96/MicroserviceSpring/
          search-paths: config-data
  application:
    name: config-service
