server:
    # Multiple instance (variable port)
    port: ${PORT:${SERVER_PORT:0}}
    # Eureka configuration
eureka:
    client:
        fetch-regitry: true
        register-with-eureka: true
        # Default port of Eureka
        service-url:
            default-zone: http://localhost:8761/eureka
    # Multiple instance (Dinamic hostname and port)   
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Integration with Zipkin
spring:
    application:
        zipkin: http://localhost:9411
