server:
    port: 8080

# Eureka configuration
eureka:
    client:
        fetch-regitry: true
        register-with-eureka: true
        
        # Default port of Eureka
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        hostname: localhost

spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                # Name of microservice in bootstrap.yml
                - id: user-service
                # Uri with loadbalancer (LB)
                  uri: lb://user-service
                  # Value of @RequestMapping of the Controller
                  predicates:
                    - Path=/user/**
                - id: car-service
                  uri: lb://car-service
                  predicates:
                    - Path=/car/**
                - id: bike-service
                  uri: lb://bike-service
                  predicates:
                    - Path=/bike/**
